#############################################################################
# Makefile for building: LoginProcess
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Apr 5 21:14:33 2011
# Project:  LoginProcess.pro
# Template: app
# Command: /usr/qtsdk-2010.05/qt/bin/qmake -spec /usr/qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile LoginProcess.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/qtsdk-2010.05/qt/mkspecs/linux-g++-64 -I. -I/usr/qtsdk-2010.05/qt/include/QtCore -I/usr/qtsdk-2010.05/qt/include/QtNetwork -I/usr/qtsdk-2010.05/qt/include/QtGui -I/usr/qtsdk-2010.05/qt/include/QtXml -I/usr/qtsdk-2010.05/qt/include/QtSql -I/usr/qtsdk-2010.05/qt/include/QtSvg -I/usr/qtsdk-2010.05/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/usr/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/qtsdk-2010.05/qt/lib -lQtSvg -L/usr/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib64 -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		loginwindow.cpp \
		User.cpp \
		loginwindowctrl.cpp \
		mapwindow.cpp \
		invalidwindow.cpp \
		genui.cpp \
		mapwinctrl.cpp \
		adduserwindow.cpp \
		adduserctrl.cpp \
		Facility.cpp \
		addfacility.cpp \
		addfacctrl.cpp \
		genctrl.cpp \
		Patient.cpp \
		Bed.cpp \
		facilitywindow.cpp \
		AddBedController.cpp \
		AssignLTCController.cpp \
		AssignHospitalController.cpp \
		AddWLController.cpp \
		MessageController.cpp \
		Message.cpp \
		xmlreader.cpp \
		facilitywinctrl.cpp \
		waitingctrl.cpp \
		waitinglistwindow.cpp \
		newpatientwindow.cpp \
		newpatientctrl.cpp \
		genreportwin.cpp \
		genreportctrl.cpp \
		removeuser.cpp \
		removeuserctrl.cpp moc_loginwindow.cpp \
		moc_mapwindow.cpp \
		moc_invalidwindow.cpp \
		moc_adduserwindow.cpp \
		moc_addfacility.cpp \
		moc_facilitywindow.cpp \
		moc_MessageController.cpp \
		moc_waitinglistwindow.cpp \
		moc_newpatientwindow.cpp \
		moc_genreportwin.cpp \
		moc_removeuser.cpp
OBJECTS       = main.o \
		loginwindow.o \
		User.o \
		loginwindowctrl.o \
		mapwindow.o \
		invalidwindow.o \
		genui.o \
		mapwinctrl.o \
		adduserwindow.o \
		adduserctrl.o \
		Facility.o \
		addfacility.o \
		addfacctrl.o \
		genctrl.o \
		Patient.o \
		Bed.o \
		facilitywindow.o \
		AddBedController.o \
		AssignLTCController.o \
		AssignHospitalController.o \
		AddWLController.o \
		MessageController.o \
		Message.o \
		xmlreader.o \
		facilitywinctrl.o \
		waitingctrl.o \
		waitinglistwindow.o \
		newpatientwindow.o \
		newpatientctrl.o \
		genreportwin.o \
		genreportctrl.o \
		removeuser.o \
		removeuserctrl.o \
		moc_loginwindow.o \
		moc_mapwindow.o \
		moc_invalidwindow.o \
		moc_adduserwindow.o \
		moc_addfacility.o \
		moc_facilitywindow.o \
		moc_MessageController.o \
		moc_waitinglistwindow.o \
		moc_newpatientwindow.o \
		moc_genreportwin.o \
		moc_removeuser.o
DIST          = /usr/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/usr/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/usr/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/usr/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/usr/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		LoginProcess.pro
QMAKE_TARGET  = LoginProcess
DESTDIR       = 
TARGET        = LoginProcess

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_loginwindow.h ui_mapwindow.h ui_invalidwindow.h ui_adduserwindow.h ui_addfacility.h ui_facilitywindow.h ui_waitinglistwindow.h ui_newpatientwindow.h ui_genreportwin.h ui_removeuser.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LoginProcess.pro  /usr/qtsdk-2010.05/qt/mkspecs/linux-g++-64/qmake.conf /usr/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/usr/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/usr/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/usr/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/usr/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/usr/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/usr/qtsdk-2010.05/qt/lib/libQtSvg.prl \
		/usr/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/usr/qtsdk-2010.05/qt/lib/libQtCore.prl \
		/usr/qtsdk-2010.05/qt/lib/libQtSql.prl \
		/usr/qtsdk-2010.05/qt/lib/libQtXml.prl \
		/usr/qtsdk-2010.05/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile LoginProcess.pro
/usr/qtsdk-2010.05/qt/mkspecs/common/g++.conf:
/usr/qtsdk-2010.05/qt/mkspecs/common/unix.conf:
/usr/qtsdk-2010.05/qt/mkspecs/common/linux.conf:
/usr/qtsdk-2010.05/qt/mkspecs/qconfig.pri:
/usr/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/debug.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/qt.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/moc.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/resources.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/uic.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/lex.prf:
/usr/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/usr/qtsdk-2010.05/qt/lib/libQtSvg.prl:
/usr/qtsdk-2010.05/qt/lib/libQtGui.prl:
/usr/qtsdk-2010.05/qt/lib/libQtCore.prl:
/usr/qtsdk-2010.05/qt/lib/libQtSql.prl:
/usr/qtsdk-2010.05/qt/lib/libQtXml.prl:
/usr/qtsdk-2010.05/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile LoginProcess.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LoginProcess1.0.0 || $(MKDIR) .tmp/LoginProcess1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LoginProcess1.0.0/ && $(COPY_FILE) --parents loginwindow.h User.h loginwindowctrl.h mapwindow.h invalidwindow.h genui.h mapwinctrl.h adduserwindow.h adduserctrl.h Facility.h addfacility.h addfacctrl.h genctrl.h Patient.h Bed.h facilitywindow.h AddBedController.h AssignLTCController.h AssignHospitalController.h AddWLController.h MessageController.h Message.h xmlreader.h facilitywinctrl.h waitingctrl.h waitinglistwindow.h newpatientwindow.h newpatientctrl.h genreportwin.h genreportctrl.h removeuser.h removeuserctrl.h .tmp/LoginProcess1.0.0/ && $(COPY_FILE) --parents main.cpp loginwindow.cpp User.cpp loginwindowctrl.cpp mapwindow.cpp invalidwindow.cpp genui.cpp mapwinctrl.cpp adduserwindow.cpp adduserctrl.cpp Facility.cpp addfacility.cpp addfacctrl.cpp genctrl.cpp Patient.cpp Bed.cpp facilitywindow.cpp AddBedController.cpp AssignLTCController.cpp AssignHospitalController.cpp AddWLController.cpp MessageController.cpp Message.cpp xmlreader.cpp facilitywinctrl.cpp waitingctrl.cpp waitinglistwindow.cpp newpatientwindow.cpp newpatientctrl.cpp genreportwin.cpp genreportctrl.cpp removeuser.cpp removeuserctrl.cpp .tmp/LoginProcess1.0.0/ && $(COPY_FILE) --parents loginwindow.ui mapwindow.ui invalidwindow.ui adduserwindow.ui addfacility.ui facilitywindow.ui waitinglistwindow.ui newpatientwindow.ui genreportwin.ui removeuser.ui .tmp/LoginProcess1.0.0/ && (cd `dirname .tmp/LoginProcess1.0.0` && $(TAR) LoginProcess1.0.0.tar LoginProcess1.0.0 && $(COMPRESS) LoginProcess1.0.0.tar) && $(MOVE) `dirname .tmp/LoginProcess1.0.0`/LoginProcess1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LoginProcess1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_loginwindow.cpp moc_mapwindow.cpp moc_invalidwindow.cpp moc_adduserwindow.cpp moc_addfacility.cpp moc_facilitywindow.cpp moc_MessageController.cpp moc_waitinglistwindow.cpp moc_newpatientwindow.cpp moc_genreportwin.cpp moc_removeuser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_loginwindow.cpp moc_mapwindow.cpp moc_invalidwindow.cpp moc_adduserwindow.cpp moc_addfacility.cpp moc_facilitywindow.cpp moc_MessageController.cpp moc_waitinglistwindow.cpp moc_newpatientwindow.cpp moc_genreportwin.cpp moc_removeuser.cpp
moc_loginwindow.cpp: loginwindowctrl.h \
		User.h \
		invalidwindow.h \
		genui.h \
		mapwindow.h \
		mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		facilitywindow.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h \
		loginwindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) loginwindow.h -o moc_loginwindow.cpp

moc_mapwindow.cpp: mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h \
		mapwindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) mapwindow.h -o moc_mapwindow.cpp

moc_invalidwindow.cpp: genui.h \
		invalidwindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) invalidwindow.h -o moc_invalidwindow.cpp

moc_adduserwindow.cpp: adduserctrl.h \
		genctrl.h \
		User.h \
		invalidwindow.h \
		genui.h \
		adduserwindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) adduserwindow.h -o moc_adduserwindow.cpp

moc_addfacility.cpp: addfacctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		addfacility.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) addfacility.h -o moc_addfacility.cpp

moc_facilitywindow.cpp: genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		Patient.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		facilitywindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) facilitywindow.h -o moc_facilitywindow.cpp

moc_MessageController.cpp: Message.h \
		xmlreader.h \
		AssignHospitalController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignLTCController.h \
		AddBedController.h \
		AddWLController.h \
		mapwinctrl.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h \
		MessageController.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) MessageController.h -o moc_MessageController.cpp

moc_waitinglistwindow.cpp: waitingctrl.h \
		Patient.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		waitinglistwindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) waitinglistwindow.h -o moc_waitinglistwindow.cpp

moc_newpatientwindow.cpp: genui.h \
		newpatientctrl.h \
		genctrl.h \
		invalidwindow.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		AssignHospitalController.h \
		newpatientwindow.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) newpatientwindow.h -o moc_newpatientwindow.cpp

moc_genreportwin.cpp: genreportctrl.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		genreportwin.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) genreportwin.h -o moc_genreportwin.cpp

moc_removeuser.cpp: removeuserctrl.h \
		invalidwindow.h \
		genui.h \
		User.h \
		genctrl.h \
		removeuser.h
	/usr/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) removeuser.h -o moc_removeuser.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_loginwindow.h ui_mapwindow.h ui_invalidwindow.h ui_adduserwindow.h ui_addfacility.h ui_facilitywindow.h ui_waitinglistwindow.h ui_newpatientwindow.h ui_genreportwin.h ui_removeuser.h
compiler_uic_clean:
	-$(DEL_FILE) ui_loginwindow.h ui_mapwindow.h ui_invalidwindow.h ui_adduserwindow.h ui_addfacility.h ui_facilitywindow.h ui_waitinglistwindow.h ui_newpatientwindow.h ui_genreportwin.h ui_removeuser.h
ui_loginwindow.h: loginwindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic loginwindow.ui -o ui_loginwindow.h

ui_mapwindow.h: mapwindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic mapwindow.ui -o ui_mapwindow.h

ui_invalidwindow.h: invalidwindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic invalidwindow.ui -o ui_invalidwindow.h

ui_adduserwindow.h: adduserwindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic adduserwindow.ui -o ui_adduserwindow.h

ui_addfacility.h: addfacility.ui
	/usr/qtsdk-2010.05/qt/bin/uic addfacility.ui -o ui_addfacility.h

ui_facilitywindow.h: facilitywindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic facilitywindow.ui -o ui_facilitywindow.h

ui_waitinglistwindow.h: waitinglistwindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic waitinglistwindow.ui -o ui_waitinglistwindow.h

ui_newpatientwindow.h: newpatientwindow.ui
	/usr/qtsdk-2010.05/qt/bin/uic newpatientwindow.ui -o ui_newpatientwindow.h

ui_genreportwin.h: genreportwin.ui
	/usr/qtsdk-2010.05/qt/bin/uic genreportwin.ui -o ui_genreportwin.h

ui_removeuser.h: removeuser.ui
	/usr/qtsdk-2010.05/qt/bin/uic removeuser.ui -o ui_removeuser.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp loginwindow.h \
		loginwindowctrl.h \
		User.h \
		invalidwindow.h \
		genui.h \
		mapwindow.h \
		mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		facilitywindow.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

loginwindow.o: loginwindow.cpp loginwindow.h \
		loginwindowctrl.h \
		User.h \
		invalidwindow.h \
		genui.h \
		mapwindow.h \
		mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		facilitywindow.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h \
		ui_loginwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwindow.o loginwindow.cpp

User.o: User.cpp User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

loginwindowctrl.o: loginwindowctrl.cpp loginwindowctrl.h \
		User.h \
		invalidwindow.h \
		genui.h \
		mapwindow.h \
		mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		facilitywindow.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwindowctrl.o loginwindowctrl.cpp

mapwindow.o: mapwindow.cpp mapwindow.h \
		mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h \
		ui_mapwindow.h \
		MessageController.h \
		Message.h \
		xmlreader.h \
		AddWLController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapwindow.o mapwindow.cpp

invalidwindow.o: invalidwindow.cpp invalidwindow.h \
		genui.h \
		ui_invalidwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o invalidwindow.o invalidwindow.cpp

genui.o: genui.cpp genui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genui.o genui.cpp

mapwinctrl.o: mapwinctrl.cpp mapwinctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h \
		MessageController.h \
		Message.h \
		xmlreader.h \
		AddWLController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapwinctrl.o mapwinctrl.cpp

adduserwindow.o: adduserwindow.cpp adduserwindow.h \
		adduserctrl.h \
		genctrl.h \
		User.h \
		invalidwindow.h \
		genui.h \
		ui_adduserwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adduserwindow.o adduserwindow.cpp

adduserctrl.o: adduserctrl.cpp adduserctrl.h \
		genctrl.h \
		User.h \
		invalidwindow.h \
		genui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adduserctrl.o adduserctrl.cpp

Facility.o: Facility.cpp Facility.h \
		Patient.h \
		Bed.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Facility.o Facility.cpp

addfacility.o: addfacility.cpp addfacility.h \
		addfacctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		ui_addfacility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addfacility.o addfacility.cpp

addfacctrl.o: addfacctrl.cpp addfacctrl.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		mapwinctrl.h \
		facilitywindow.h \
		facilitywinctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addfacctrl.o addfacctrl.cpp

genctrl.o: genctrl.cpp genctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genctrl.o genctrl.cpp

Patient.o: Patient.cpp Patient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Patient.o Patient.cpp

Bed.o: Bed.cpp Bed.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bed.o Bed.cpp

facilitywindow.o: facilitywindow.cpp facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		Patient.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		ui_facilitywindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facilitywindow.o facilitywindow.cpp

AddBedController.o: AddBedController.cpp AddBedController.h \
		Bed.h \
		User.h \
		Facility.h \
		Patient.h \
		mapwinctrl.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddBedController.o AddBedController.cpp

AssignLTCController.o: AssignLTCController.cpp AssignLTCController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AssignLTCController.o AssignLTCController.cpp

AssignHospitalController.o: AssignHospitalController.cpp AssignHospitalController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h \
		mapwinctrl.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AssignHospitalController.o AssignHospitalController.cpp

AddWLController.o: AddWLController.cpp AddWLController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h \
		mapwinctrl.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddWLController.o AddWLController.cpp

MessageController.o: MessageController.cpp MessageController.h \
		Message.h \
		xmlreader.h \
		AssignHospitalController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignLTCController.h \
		AddBedController.h \
		AddWLController.h \
		mapwinctrl.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MessageController.o MessageController.cpp

Message.o: Message.cpp Message.h \
		MessageController.h \
		xmlreader.h \
		AssignHospitalController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignLTCController.h \
		AddBedController.h \
		AddWLController.h \
		mapwinctrl.h \
		facilitywindow.h \
		genui.h \
		facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		invalidwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Message.o Message.cpp

xmlreader.o: xmlreader.cpp xmlreader.h \
		AssignHospitalController.h \
		Patient.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignLTCController.h \
		AddBedController.h \
		AddWLController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlreader.o xmlreader.cpp

facilitywinctrl.o: facilitywinctrl.cpp facilitywinctrl.h \
		genctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		Patient.h \
		invalidwindow.h \
		genui.h \
		newpatientwindow.h \
		newpatientctrl.h \
		Facility.h \
		Bed.h \
		User.h \
		AssignHospitalController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facilitywinctrl.o facilitywinctrl.cpp

waitingctrl.o: waitingctrl.cpp waitingctrl.h \
		Patient.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		mapwinctrl.h \
		Facility.h \
		Bed.h \
		User.h \
		facilitywindow.h \
		facilitywinctrl.h \
		waitinglistwindow.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		genreportctrl.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waitingctrl.o waitingctrl.cpp

waitinglistwindow.o: waitinglistwindow.cpp waitinglistwindow.h \
		waitingctrl.h \
		Patient.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		ui_waitinglistwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waitinglistwindow.o waitinglistwindow.cpp

newpatientwindow.o: newpatientwindow.cpp newpatientwindow.h \
		genui.h \
		newpatientctrl.h \
		genctrl.h \
		invalidwindow.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		AssignHospitalController.h \
		ui_newpatientwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newpatientwindow.o newpatientwindow.cpp

newpatientctrl.o: newpatientctrl.cpp newpatientctrl.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		AssignHospitalController.h \
		facilitywinctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newpatientctrl.o newpatientctrl.cpp

genreportwin.o: genreportwin.cpp genreportwin.h \
		genreportctrl.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		ui_genreportwin.h \
		mapwinctrl.h \
		facilitywindow.h \
		facilitywinctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genreportwin.o genreportwin.cpp

genreportctrl.o: genreportctrl.cpp genreportctrl.h \
		genctrl.h \
		invalidwindow.h \
		genui.h \
		Facility.h \
		Patient.h \
		Bed.h \
		User.h \
		mapwinctrl.h \
		facilitywindow.h \
		facilitywinctrl.h \
		waitinglistwindow.h \
		waitingctrl.h \
		newpatientwindow.h \
		newpatientctrl.h \
		AssignHospitalController.h \
		AddBedController.h \
		AssignLTCController.h \
		addfacctrl.h \
		adduserctrl.h \
		adduserwindow.h \
		addfacility.h \
		genreportwin.h \
		removeuser.h \
		removeuserctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genreportctrl.o genreportctrl.cpp

removeuser.o: removeuser.cpp removeuser.h \
		removeuserctrl.h \
		invalidwindow.h \
		genui.h \
		User.h \
		genctrl.h \
		ui_removeuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o removeuser.o removeuser.cpp

removeuserctrl.o: removeuserctrl.cpp removeuserctrl.h \
		invalidwindow.h \
		genui.h \
		User.h \
		genctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o removeuserctrl.o removeuserctrl.cpp

moc_loginwindow.o: moc_loginwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwindow.o moc_loginwindow.cpp

moc_mapwindow.o: moc_mapwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapwindow.o moc_mapwindow.cpp

moc_invalidwindow.o: moc_invalidwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_invalidwindow.o moc_invalidwindow.cpp

moc_adduserwindow.o: moc_adduserwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adduserwindow.o moc_adduserwindow.cpp

moc_addfacility.o: moc_addfacility.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addfacility.o moc_addfacility.cpp

moc_facilitywindow.o: moc_facilitywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_facilitywindow.o moc_facilitywindow.cpp

moc_MessageController.o: moc_MessageController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MessageController.o moc_MessageController.cpp

moc_waitinglistwindow.o: moc_waitinglistwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waitinglistwindow.o moc_waitinglistwindow.cpp

moc_newpatientwindow.o: moc_newpatientwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newpatientwindow.o moc_newpatientwindow.cpp

moc_genreportwin.o: moc_genreportwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_genreportwin.o moc_genreportwin.cpp

moc_removeuser.o: moc_removeuser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_removeuser.o moc_removeuser.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

